spring:
  jpa:
    show-sql: true
  datasource:
    #url: jdbc:mysql://repick.iptime.org:23306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true # 새로 추가된 옵션 schema 가 없는 경우 생성
    url: jdbc:mysql://repick.iptime.org:23306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath:schema.sql  # 새로 추가된 옵션 src/main/resource/schema.sql
    #initialization-mode: always   # 새로 추가된 옵션 위의 schema.sql 파일을 실행 시켜 준다.
logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: error
    org.hibernate.SQL: error
    hibernate.type.descriptor.sql.BasicBinder: error